/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Ablauf.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Ablauf: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Ablauf()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hallo, wie geht es dir?");
		yield return lineBreak();
		yield return link("Gut", "Gut", null);
		yield return lineBreak();
		yield return link("Schlecht", "Schlecht", null);
		yield return lineBreak();
		yield return link("Naja", "Naja", null);
		yield break;
	}


	// .............
	// #2: Gut

	void passage2_Init()
	{
		this.Passages[@"Gut"] = new StoryPassage(@"Gut", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Na dann, hast du Lust auf Fussball?");
		yield return lineBreak();
		yield return link("Ja", "Ja", null);
		yield return lineBreak();
		yield return link("Nein", "Nein", null);
		yield return lineBreak();
		yield return link("Später", "Später", null);
		yield break;
	}


	// .............
	// #3: Schlecht

	void passage3_Init()
	{
		this.Passages[@"Schlecht"] = new StoryPassage(@"Schlecht", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Was ist den los?");
		yield return lineBreak();
		yield return link("Bin krank", "Bin krank", null);
		yield return lineBreak();
		yield return link("Geht dich nichts an", "Geht dich nichts an", null);
		yield return lineBreak();
		yield return link("Schlecht geschlafen", "Schlecht geschlafen", null);
		yield break;
	}


	// .............
	// #4: Naja

	void passage4_Init()
	{
		this.Passages[@"Naja"] = new StoryPassage(@"Naja", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Was heisst das?");
		yield return lineBreak();
		yield return link("Etwas erkältet", "Etwas erkältet", null);
		yield return lineBreak();
		yield return link("Die Ferien sind bald vorbei", "Die Ferien sind bald vorbei", null);
		yield break;
	}


	// .............
	// #5: Ja

	void passage5_Init()
	{
		this.Passages[@"Ja"] = new StoryPassage(@"Ja", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #6: Nein

	void passage6_Init()
	{
		this.Passages[@"Nein"] = new StoryPassage(@"Nein", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #7: Später

	void passage7_Init()
	{
		this.Passages[@"Später"] = new StoryPassage(@"Später", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #8: Bin krank

	void passage8_Init()
	{
		this.Passages[@"Bin krank"] = new StoryPassage(@"Bin krank", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #9: Geht dich nichts an

	void passage9_Init()
	{
		this.Passages[@"Geht dich nichts an"] = new StoryPassage(@"Geht dich nichts an", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #10: Schlecht geschlafen

	void passage10_Init()
	{
		this.Passages[@"Schlecht geschlafen"] = new StoryPassage(@"Schlecht geschlafen", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #11: Etwas erkältet

	void passage11_Init()
	{
		this.Passages[@"Etwas erkältet"] = new StoryPassage(@"Etwas erkältet", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #12: Die Ferien sind bald vorbei

	void passage12_Init()
	{
		this.Passages[@"Die Ferien sind bald vorbei"] = new StoryPassage(@"Die Ferien sind bald vorbei", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return link("Start", "Start", null);
		yield break;
	}


}