/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: NeueGeschichte.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @NeueGeschichte: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@NeueGeschichte()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hallo");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wie geht es dir?");
		yield return lineBreak();
		yield return link("Geht mir gut", "Geht mir gut", null);
		yield return lineBreak();
		yield return link("Geht mir nicht gut", "Geht mir nicht gut", null);
		yield break;
	}


	// .............
	// #2: Geht mir gut

	void passage2_Init()
	{
		this.Passages[@"Geht mir gut"] = new StoryPassage(@"Geht mir gut", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #3: Geht mir nicht gut

	void passage3_Init()
	{
		this.Passages[@"Geht mir nicht gut"] = new StoryPassage(@"Geht mir nicht gut", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}