/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: NeuerTest.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @NeuerTest: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@NeuerTest()
	{
		this.StartPassage = "Beginn";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Beginn

	void passage1_Init()
	{
		this.Passages[@"Beginn"] = new StoryPassage(@"Beginn", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hallo, ich bin es.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wie geht es dir?");
		yield return lineBreak();
		yield return link("Gut", "Gut", null);
		yield return lineBreak();
		yield return link("Schlecht", "Schlecht", null);
		yield break;
	}


	// .............
	// #2: Gut

	void passage2_Init()
	{
		this.Passages[@"Gut"] = new StoryPassage(@"Gut", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #3: Schlecht

	void passage3_Init()
	{
		this.Passages[@"Schlecht"] = new StoryPassage(@"Schlecht", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}