/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Test2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Test2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Test2()
	{
		this.StartPassage = "Beginn";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Beginn

	void passage1_Init()
	{
		this.Passages[@"Beginn"] = new StoryPassage(@"Beginn", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hallo");
		yield return lineBreak();
		yield return link("Hallo", "Hallo", null);
		yield break;
	}


	// .............
	// #2: Hallo

	void passage2_Init()
	{
		this.Passages[@"Hallo"] = new StoryPassage(@"Hallo", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Alles klar?");
		yield return lineBreak();
		yield return link("Ja", "Ja", null);
		yield return lineBreak();
		yield return link("Nein", "Nein", null);
		yield break;
	}


	// .............
	// #3: Ja

	void passage3_Init()
	{
		this.Passages[@"Ja"] = new StoryPassage(@"Ja", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #4: Nein

	void passage4_Init()
	{
		this.Passages[@"Nein"] = new StoryPassage(@"Nein", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Was ist den los?");
		yield return lineBreak();
		yield return link("bin krank", "bin krank", null);
		yield return lineBreak();
		yield return link("Wollte eigentlich nach Australien in die Ferien", "Wollte eigentlich nach Australien in die Ferien", null);
		yield return lineBreak();
		yield return link("Geht dich nichts an", "Geht dich nichts an", null);
		yield break;
	}


	// .............
	// #5: bin krank

	void passage5_Init()
	{
		this.Passages[@"bin krank"] = new StoryPassage(@"bin krank", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #6: Wollte eigentlich nach Australien in die Ferien

	void passage6_Init()
	{
		this.Passages[@"Wollte eigentlich nach Australien in die Ferien"] = new StoryPassage(@"Wollte eigentlich nach Australien in die Ferien", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Kannst du nicht?");
		yield return lineBreak();
		yield return link("Nein", "Nein", null);
		yield return lineBreak();
		yield return link("Nein, wegen Corona", "Nein, wegen Corona", null);
		yield return lineBreak();
		yield return link("blabla", "blabla", null);
		yield return lineBreak();
		yield return link("tutututu", "tutututu", null);
		yield break;
	}


	// .............
	// #7: Geht dich nichts an

	void passage7_Init()
	{
		this.Passages[@"Geht dich nichts an"] = new StoryPassage(@"Geht dich nichts an", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #8: Nein, wegen Corona

	void passage8_Init()
	{
		this.Passages[@"Nein, wegen Corona"] = new StoryPassage(@"Nein, wegen Corona", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #9: blabla

	void passage9_Init()
	{
		this.Passages[@"blabla"] = new StoryPassage(@"blabla", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #10: tutututu

	void passage10_Init()
	{
		this.Passages[@"tutututu"] = new StoryPassage(@"tutututu", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}